= Grover’s search algorithm

This is Lov Grover’s famous search algorithm that, according to
theory, runs in approximately (π/4)√N time.

Grover designed the algorithm for hybrid computers made of
superconducting components. There is a theory that such hardware
attracts “invisible tooth fairies” who form a chain by holding hands,
to make the algorithm function. Actually the mathematics is the same
no matter how you construct the hardware. You could make it in silicon
from linear CMOS or operational amplifiers.

_Indeed, here you will find an electronics project for high frequency
op amps._

The secret of the algorithm is not “tooth fairies” but phase-locked
oscillators.

However, it makes a lot more sense to use a digital computer.

There is no such thing as a “tooth fairy.” Quantum theory is nonsense.
When it was taught to me in the 1980s with explicit orders not to
think, and just do the calculations, that was a sign something was
amiss. Quantum theory is a cause of cerebral paralysis and should be
banned by university faculties.

But the literature is completely wrong about the speed of Grover’s
algorithm. It is actually much, much faster than (π/4)√N. This would
be widely known already, had the algorithm been analyzed by numerical
analysts who had never been exposed to quantum theory.

First there is a point that is obvious to any truly practical
programmer, which is that, for a problem like searching an array, the
size of the amplitudes array is bounded by the size of a pointer, and
thus is on the order of a _constant_. Nevertheless, according to
“tooth fairy” theory you have to run the computation for a full number
of iterations. Otherwise the “tooth fairies” cannot complete their
spell. This is known as the _Principle of Niels Bohr was a Fruitcake
Wrapped in a Nutroll_. A consequence of this is Grover’s algorithm is
slow as molasses, and it is commonly thought this is an impasse.

_In fact Grover’s algorithm is lightning fast._ You can stop the
algorithm whenever there is an indication it has reached a conclusion.
This is true whether the hardware is analog or digital. Our
implementations look for such indications.

***

_But (we now realize) a brute force parallel search is even faster._
And must be faster than _any_ “quantum” algorithm. It takes better
advantage of the hardware, whether the hardware be digital or analog,
for this simple reason: _the oracle alone is a device that solves the
problem_.

To build a device that executes Grover’s algorithm, or to program a
device to execute Grover’s algorithm, you must construct an “oracle”
that already, by itself, solves the problem! It is only superstitions
decreed by the Church of Complementarity, entirely without
experimental support, that prevent use of that solution directly,
instead of as “oracle” in an enormous deep freeze.

Nevertheless, the algorithm presented here is of scientific interest.
It demonstrates that even in the algorithm of the Josephson deep
freeze you can stop at any time, and that you do not need the
Josephson deep freeze. _There is no such thing as a “wavefunction.”
Niels Bohr was a cult founder. Until you break free of his doctrines,
you belong to a cult rather than a scientific community._

Also, it is possible your oracle’s output is difficult to read without
a phase-lock device to do that reading. In that case, Grover’s design
may be what you need. However, you need no cryogenics and need not
worry about _any_ Copenhagen-interpretation doctrines. They are all
ecclesiastical decrees without experimental support. If you try to
find foundational experiments to back them up, you will not find
these. You will find only the supposed foundational experiments of
“quantum” physics, which are merely experiments physicists did not
solve using Maxwell’s equations.footnote:[Physicists never developed
the habit of using Maxwell’s equations rigorously. Einstein, for
instance, unrigorously treated _c_ as “the speed of light in a
vacuum.” It is no such thing. It is the speed of waves in a Maxwellian
electromagnetic field. The different definition leads to the Unified
Field Theory instead of Special Relativity, and preserves intuitive
three-dimensional space and time. The Michelson-Morley experiment
requires the energy density of electromagnetism also be mass density,
so the waves will have inertia. Thus the whole thing _begins_ with
_dE=c²dm_.] They are solved using Maxwell’s equations at
https://github.com/chemoelectric/iris-numbers-and-unified-field-theory
in Volume{nbsp}IV.

***

IMPORTANT: I AM A DISABLED SENIOR CITIZEN. PLEASE DO NOT BOTHER ME.
ALL OF THIS STUFF IS DONATED TO THE PUBLIC DOMAIN FOR OTHERS TO DEAL
WITH WHILE LEAVING ME ALONE. You can read snapshots of my research at
https://github.com/chemoelectric/iris-numbers-and-unified-field-theory
